databases:
  - name: postgresql_f7qf
    databaseName: postgresql_f7qf
    user: postgresql_f7qf_user

services:
  - type: web
    name: gets_ready_website
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql_f7qf
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false